# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCreatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chara',
            fields=[
                ('timecreatable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charative.TimeCreatable')),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='chara_images')),
            ],
            options={
                'abstract': False,
            },
            bases=('charative.timecreatable', models.Model),
        ),
    ]
