# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, upload_to='user_avatars')),
                ('short_bio', models.TextField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chara',
            name='timecreatable_ptr',
        ),
        migrations.DeleteModel(
            name='Chara',
        ),
        migrations.DeleteModel(
            name='TimeCreatable',
        ),
    ]
