# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charative', '0002_auto_20171108_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='chara_images')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
