# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charative', '0003_chara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RomanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='romance_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(to='charative.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='romance_type',
            field=models.ManyToManyField(to='charative.RomanceType'),
        ),
    ]
