# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charative', '0004_auto_20171109_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
